project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "AI Impact"
  author:
    - ANNIKA GUPTA (ag5170)
  repo-url: https://github.com/annikag27/AICarbonFootprint
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


